server:
  port: 4080
  host: "127.0.0.1"

# 存储设置
storage:
  upload_dir: "./uploads" # 上传文件保存路径
  log_dir: "./logs" # 日志保存路径
  max_file_size: 104857600  # 上传文件大小限制 100MB in bytes
  database_path: "./logs_v1.db"  # SQLite数据库文件路径

log_levels:
  ERROR: "#dc3545"    # 红色
  WARN: "#ffc107"     # 黄色
  INFO: "#17a2b8"     # 蓝色
  DEBUG: "#6c757d"    # 灰色
  FATAL: "#721c24"    # 深红色
  TRACE: "#6f42c1"    # 紫色
  UNKNOWN: "#343a40"  # 黑色

filters:
  default_levels: ["ERROR", "WARN", "INFO"]
  exclude_patterns: []
  include_patterns: []

ai:
  api_key: "sk-2d7b4b20d97d47bfbeb0cdd6b872b70f"
  model: "qwen3-coder-flash-2025-07-28"